In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('LifeExpectancyData.csv')

In [9]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [10]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [14]:
min_life_expectancy = df[df['Life expectancy '] == 36.300000]
min_life_expectancy

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1127,Haiti,2010,Developing,36.3,682.0,23,5.76,36.292918,NaN,0,...,66.0,8.9,66.0,1.9,662.279518,9999617.0,4.0,4.0,0.47,8.6

In [15]:
haiti = df[df['Country'] == 'Haiti']
haiti

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1122,Haiti,2015,Developing,63.5,24.0,14,NaN,0.000000,6.0,0,...,56.0,NaN,6.0,0.5,814.546395,171161.0,3.9,3.9,0.490,9.1
1123,Haiti,2014,Developing,63.1,245.0,14,0.01,5.103249,48.0,0,...,55.0,7.56,48.0,0.5,83.114812,1572466.0,3.9,3.9,0.487,9.1
1124,Haiti,2013,Developing,62.7,253.0,14,5.68,4.989712,68.0,0,...,67.0,8.10,68.0,0.5,81.265673,1431776.0,3.9,3.9,0.483,9.1
1125,Haiti,2012,Developing,62.3,259.0,15,5.68,26.379425,NaN,0,...,67.0,9.88,67.0,0.8,766.843762,128921.0,3.9,3.9,0.477,8.9
1126,Haiti,2011,Developing,62.3,259.0,15,5.68,4.106484,NaN,0,...,67.0,1.41,68.0,1.5,74.935845,114554.0,4.0,4.0,0.470,8.7
1127,Haiti,2010,Developing,36.3,682.0,23,5.76,36.292918,NaN,0,...,66.0,8.90,66.0,1.9,662.279518,9999617.0,4.0,4.0,0.470,8.6
1128,Haiti,2009,Developing,62.5,251.0,16,5.85,41.300795,NaN,0,...,65.0,6.68,65.0,2.0,668.297646,985287.0,4.1,4.1,0.466,8.5
1129,Haiti,2008,Developing,62.1,259.0,16,5.95,63.831957,NaN,0,...,64.0,5.92,63.0,2.4,674.756415,97529.0,4.2,4.2,0.462,8.4
1130,Haiti,2007,Developing,61.8,266.0,17,6.08,56.778587,NaN,0,...,62.0,5.56,63.0,2.7,615.819819,9556889.0,4.2,4.2,0.458,8.4
1131,Haiti,2006,Developing,61.1,28.0,17,6.18,6.995556,NaN,0,...,61.0,5.70,6.0,3.3,55.476260,949457.0,4.3,4.3,0.455,8.3
1132,Haiti,2005,Developing,65.0,29.0,17,5.57,38.109043,NaN,0,...,6.0,4.41,6.0,3.9,465.311876,926344.0,4.4,4.4,0.452,8.2
1133,Haiti,2004,Developing,58.7,32.0,18,6.10,64.398533,NaN,0,...,58.0,5.61,55.0,4.3,387.942972,9119178.0,4.5,4.5,0.450,8.1
1134,Haiti,2003,Developing,59.7,3.0,18,6.64,44.256871,NaN,0,...,56.0,5.32,53.0,4.6,329.782946,8976552.0,4.5,4.6,0.447,8.1
1135,Haiti,2002,Developing,59.3,33.0,19,6.10,50.285582,NaN,0,...,54.0,5.47,48.0,4.8,393.163270,8834733.0,4.6,4.7,0.444,8.0
1136,Haiti,2001,Developing,58.9,35.0,19,6.22,60.778159,NaN,159,...,52.0,5.63,45.0,5.0,413.738316,8692567.0,4.7,4.7,0.443,7.9
1137,Haiti,2000,Developing,58.6,35.0,20,4.79,74.460330,NaN,992,...,5.0,6.60,41.0,5.1,462.486524,85492.0,4.8,4.8,0.439,7.8

In [16]:
max_infant_deaths = df[df['infant deaths'] == 1800.000000]
max_infant_deaths

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1200,India,2001,Developing,62.9,222.0,1800,1.00,19.003406,NaN,51780,...,58.0,4.50,59.0,0.3,447.138966,171477855.0,27.5,28.5,0.494,8.3
1201,India,2000,Developing,62.5,224.0,1800,0.93,19.266157,NaN,38835,...,57.0,4.26,58.0,0.3,438.864634,1535912.0,27.7,28.6,0.489,8.3

In [17]:
india = df[df['Country'] == 'India']
india

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1186,India,2015,Developing,68.3,181.0,910,NaN,0.000000,87.0,90387,...,86.0,NaN,87.0,0.2,1613.188780,1.395398e+06,26.7,27.3,0.615,11.6
1187,India,2014,Developing,68.0,184.0,957,3.07,86.521539,79.0,79563,...,84.0,4.69,85.0,0.2,1573.118890,1.293859e+09,26.8,27.4,0.607,11.6
1188,India,2013,Developing,67.6,187.0,1000,3.11,67.672304,7.0,13822,...,82.0,4.53,83.0,0.2,1452.195373,1.278562e+08,26.8,27.5,0.599,11.5
1189,India,2012,Developing,67.3,19.0,1100,3.10,64.969645,73.0,18668,...,79.0,4.39,82.0,0.2,1446.985410,1.263659e+08,26.9,27.6,0.590,11.3
1190,India,2011,Developing,66.8,193.0,1100,3.00,64.605901,44.0,33634,...,79.0,4.33,82.0,0.2,1461.671957,1.247236e+08,26.9,27.7,0.580,10.8
1191,India,2010,Developing,66.4,196.0,1200,2.77,57.733599,38.0,31458,...,76.0,4.28,79.0,0.2,1345.771530,1.239869e+07,27.0,27.8,0.569,10.4
1192,India,2009,Developing,66.0,2.0,1300,2.50,0.844186,37.0,56188,...,73.0,4.38,74.0,0.2,19.317765,1.214271e+08,27.0,27.8,0.563,10.5
1193,India,2008,Developing,65.5,23.0,1300,1.93,43.030433,29.0,44258,...,69.0,4.34,7.0,0.3,991.484634,1.197147e+08,27.0,27.9,0.556,10.2
1194,India,2007,Developing,65.2,26.0,1400,1.59,5.234770,6.0,41144,...,67.0,4.23,64.0,0.3,118.166373,1.179681e+09,27.1,28.0,0.546,9.9
1195,India,2006,Developing,64.8,28.0,1500,1.37,34.859427,6.0,64185,...,66.0,4.25,65.0,0.3,792.259698,1.161978e+09,27.1,28.0,0.536,9.7
1196,India,2005,Developing,64.4,211.0,1500,1.27,3.509637,8.0,36711,...,65.0,4.28,65.0,0.3,77.819000,1.144119e+09,27.2,28.1,0.526,9.4
1197,India,2004,Developing,64.0,214.0,1600,1.20,27.338009,6.0,55443,...,58.0,4.22,63.0,0.3,621.318377,1.126136e+09,27.2,28.2,0.518,9.2
1198,India,2003,Developing,63.7,216.0,1700,1.19,19.480868,NaN,47147,...,57.0,4.30,61.0,0.3,541.135228,1.182785e+07,27.3,28.3,0.505,8.6
1199,India,2002,Developing,63.3,219.0,1700,1.10,17.812056,NaN,40044,...,58.0,4.40,59.0,0.3,466.284200,1.898711e+07,27.4,28.4,0.499,8.4
1200,India,2001,Developing,62.9,222.0,1800,1.00,19.003406,NaN,51780,...,58.0,4.50,59.0,0.3,447.138966,1.714779e+08,27.5,28.5,0.494,8.3
1201,India,2000,Developing,62.5,224.0,1800,0.93,19.266157,NaN,38835,...,57.0,4.26,58.0,0.3,438.864634,1.535912e+06,27.7,28.6,0.489,8.3

In [22]:
year_2015 = df[df['Year'] == 2015]
year_2015_sort_by_infant_deaths = year_2015.sort_values(by = 'infant deaths', ascending=False)
year_2015_sort_by_infant_deaths.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1186,India,2015,Developing,68.3,181.0,910,NaN,0.0,87.0,90387,...,86.0,NaN,87.0,0.2,1613.188780,1395398.0,26.7,27.3,0.615,11.6
1893,Nigeria,2015,Developing,54.5,344.0,483,NaN,0.0,49.0,12423,...,49.0,NaN,49.0,3.7,2655.157977,181181744.0,9.8,9.7,0.525,10.0
1942,Pakistan,2015,Developing,66.4,161.0,352,NaN,0.0,72.0,386,...,72.0,NaN,72.0,0.1,1431.244865,18938513.0,19.2,19.6,0.548,8.1
721,Democratic Republic of the Congo,2015,Developing,59.8,258.0,236,NaN,0.0,81.0,5020,...,78.0,NaN,81.0,1.1,NaN,NaN,9.5,9.3,NaN,NaN
560,China,2015,Developing,76.1,85.0,157,NaN,0.0,99.0,42361,...,99.0,NaN,99.0,0.1,869.211938,137122.0,3.6,2.9,0.734,13.5

In [23]:
nigeria = df[df['Country'] == 'Nigeria']
nigeria

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1893,Nigeria,2015,Developing,54.5,344.0,483,NaN,0.000000,49.0,12423,...,49.0,NaN,49.0,3.7,2655.157977,181181744.0,9.8,9.7,0.525,10.0
1894,Nigeria,2014,Developing,53.6,362.0,490,0.01,263.211103,49.0,6855,...,49.0,3.67,49.0,3.9,3221.678128,1764652.0,1.1,9.9,0.521,10.0
1895,Nigeria,2013,Developing,53.2,367.0,498,8.30,194.203288,46.0,52852,...,46.0,3.70,46.0,3.9,2996.964320,17182933.0,1.4,1.2,0.514,9.8
1896,Nigeria,2012,Developing,52.7,374.0,505,8.54,204.718626,42.0,6447,...,42.0,3.30,42.0,4.4,2755.297787,167297284.0,1.7,1.6,0.507,9.7
1897,Nigeria,2011,Developing,52.3,375.0,513,8.75,187.573319,46.0,18843,...,48.0,3.69,48.0,4.7,2527.942300,16287776.0,11.0,1.9,0.500,9.6
1898,Nigeria,2010,Developing,52.0,374.0,521,8.90,133.123087,49.0,8491,...,54.0,3.47,54.0,4.8,2327.326700,158578261.0,11.3,11.2,0.492,9.5
1899,Nigeria,2009,Developing,51.6,376.0,527,9.05,14.567647,63.0,1272,...,66.0,4.24,63.0,4.9,197.661422,15442181.0,11.7,11.6,0.487,9.3
1900,Nigeria,2008,Developing,59.0,386.0,536,9.30,105.591063,41.0,9960,...,6.0,4.00,53.0,5.0,1383.893354,1534739.0,12.0,11.9,0.481,9.2
1901,Nigeria,2007,Developing,55.0,388.0,542,9.55,104.474644,42.0,2613,...,54.0,4.47,42.0,5.2,1136.829645,14641724.0,12.3,12.3,0.477,9.1
1902,Nigeria,2006,Developing,49.8,396.0,549,9.66,10.357794,27.0,704,...,46.0,3.66,4.0,5.3,119.743286,14261494.0,12.6,12.6,0.466,9.0
1903,Nigeria,2005,Developing,49.2,4.0,556,9.71,6.416253,18.0,110927,...,45.0,4.11,36.0,5.4,87.893874,138939478.0,12.9,12.9,0.463,8.9
1904,Nigeria,2004,Developing,48.5,47.0,563,9.76,57.225558,NaN,31521,...,43.0,4.33,33.0,5.4,648.815852,135393616.0,13.2,13.2,0.445,8.5
1905,Nigeria,2003,Developing,48.1,41.0,567,9.75,30.195508,NaN,141258,...,42.0,4.50,29.0,5.4,512.657190,131972533.0,13.5,13.6,0.000,8.1
1906,Nigeria,2002,Developing,47.7,49.0,571,9.61,17.137754,NaN,42007,...,4.0,2.43,25.0,5.3,459.457212,12866671.0,13.8,13.8,0.000,7.7
1907,Nigeria,2001,Developing,47.4,48.0,574,9.58,15.830985,NaN,168107,...,36.0,3.25,27.0,5.1,351.799667,125463434.0,14.1,14.1,0.000,8.0
1908,Nigeria,2000,Developing,47.1,45.0,576,9.23,22.481776,NaN,212183,...,31.0,2.84,29.0,4.9,379.119326,1223529.0,14.3,14.4,0.000,7.6

In [24]:
max_adult_mortality = df[df['Adult Mortality'] == 723.000000]
max_adult_mortality

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.0,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2

In [ ]:
zimbabwe = df[df['Country'] == 'Zimbabwe']
zimbabwe